### PR TITLE
Create 2024-02-02-AuthOMath-ME-PHHD.md

### PR DESCRIPTION
**Pull request by guidopinkernell**
Announcing the AuthOMath project's first online multiplier event, hosted at the PHHD

### CODE REVIEW

**Comment by sangwinc** [comment]
Thanks Guido.  @KZerva can you please merge this into the master branch, (hence updating the website) and check all the links etc. are in place.  @guidopinkernell has just provided a new page of information. We'll need to add in some links.

**Comment by KZerva** [comment]
I think it's ready now.

**Comment by guidopinkernell** [comment]
Just checked: It is online now - thanks, Konstantina!

Am Dienstag, 16. Januar 2024, 11:41:06 CET schrieb Konstantina Zerva:
> I think it's ready now.


-- 
Prof. Dr. Guido Pinkernell

Pädagogische Hochschule Heidelberg
Institut für Mathematik und Informatik
Im Neuenheimer Feld 561
69120 Heidelberg
Tel.: 06221/477-567

www.pinkernell.online

**Comment by sangwinc** [comment]
Thanks!

**Pull request closed without merging**
